dist: xenial
language: python
sudo: true
python:
  - "3.7"
services:
  - docker
install:
  - docker build --file Dockerfile.database --tag rubbish-db .
  - docker run -d
      --name rubbish-db-container
      -e POSTGRES_DB=rubbish
      -e POSTGRES_USER=rubbish-test-user
      -e POSTGRES_PASSWORD=polkstreet
      -p 5432:5432 rubbish-db:latest
  - chmod +x scripts/wait_for_postgres.sh && ./scripts/wait_for_postgres.sh
  - docker exec -it rubbish-db-container alembic -c test_alembic.ini upgrade head

  - sudo apt update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - conda create -c conda-forge -q -n test-environment python=$TRAVIS_PYTHON_VERSION geopandas geopy osmnx scipy
  - conda activate test-environment
  - pip install git+https://github.com/geopandas/geopandas.git@3cba9
  - pushd python/rubbish_geo_common && pip install . && popd
  - pushd python/rubbish_geo_client && pip install .[develop] && popd
  - pushd python/rubbish_geo_admin  && pip install .[develop] && popd
script:
  - pytest python/rubbish_geo_admin/tests/tests.py
  - pytest python/rubbish_geo_client/tests/tests.py
